//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsPhoneClient.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsPhoneClient.UI.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не може да бъде показана информация за партньорите.
        /// </summary>
        public static string CannotLoadPartnersInformation {
            get {
                return ResourceManager.GetString("CannotLoadPartnersInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Около мен.
        /// </summary>
        public static string HomePageAroundMe {
            get {
                return ResourceManager.GetString("HomePageAroundMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Намерете около Вас.
        /// </summary>
        public static string HomePageFindAroundYou {
            get {
                return ResourceManager.GetString("HomePageFindAroundYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарежда се информация за партньорите.
        /// </summary>
        public static string HomePagePartnersLoadingMessage {
            get {
                return ResourceManager.GetString("HomePagePartnersLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string HomePageTemplateInfoContent {
            get {
                return ResourceManager.GetString("HomePageTemplateInfoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта.
        /// </summary>
        public static string HomePageTemplateMapContent {
            get {
                return ResourceManager.GetString("HomePageTemplateMapContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За да използвате приложението е необходимо локацията да е активна. Ще бъдете пренасочени към настройките на локацията.
        /// </summary>
        public static string LocationTurnedOffMessage {
            get {
                return ResourceManager.GetString("LocationTurnedOffMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пренасочване.
        /// </summary>
        public static string RedirectionTitle {
            get {
                return ResourceManager.GetString("RedirectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bg-BG.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колко е свободно около Вас?.
        /// </summary>
        public static string ShowAndShareHowMuchFreeTitle {
            get {
                return ResourceManager.GetString("ShowAndShareHowMuchFreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнови.
        /// </summary>
        public static string ShowAndShareRefreshContent {
            get {
                return ResourceManager.GetString("ShowAndShareRefreshContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сподели.
        /// </summary>
        public static string ShowAndShareShareButtonText {
            get {
                return ResourceManager.GetString("ShowAndShareShareButtonText", resourceCulture);
            }
        }
    }
}
